name: stc_health
description: A new Flutter project.  
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  page_transition: ^2.1.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
     - assets/images/
 
  fonts:
     - family: OpenSans Bold
       fonts:
         - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
     - family: OpenSans Regular
       fonts:
         - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf

 
 
